name: Dev Pull Request Workflow

on:
  pull_request:
    branches:
      - master

env:
  RANDORIKATA__APP_NAME: randori-kata
  RANDORIKATA__CODE__APP_NAME: randori-kata-code
  RANDORIKATA__CODE__DROPLET_SIZE: s-1vcpu-1gb
  RANDORIKATA__ENV: test

jobs:
  run_tests:
    name: Setup Digital Ocean Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: ${{ env.GITHUB_REF }}

      - name: NPM Install On Github Action
        run: npm install .

      - name: Run Tests
        run: |
          export NODE_ENV=$RANDORIKATA__ENV
          npm test
